version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-deploy-prod:
    executor:
      name: node/default
    steps:
      - run:
          name: 'Create directory'
          command: mkdir -p ~/my-repo
      - checkout:
          path: ~/my-repo
      - aws-s3/copy:
          arguments: '--recursive'
          from: my-repo
          to: "s3://stashng-website"
      - run:
          name: 'List current directory'
          command: ls my-repo
      - run: echo "Successfully deployed to the bucket accessible to CloudFront"

workflows:
  version: 2
  build-publish-and-deploy:
    jobs:
      - build-deploy-prod:
          filters:
            branches:
              only:
                - main
