version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build-deploy-prod:
    executor:
      name: node/default
    steps:
      - aws-s3/copy:
          arguments: '--recursive'
          from: $CIRCLE_WORKING_DIRECTORY
          to: "s3://stashng-website"
      - run: 
          name: 'List current directory'
          command: ls $CIRCLE_WORKING_DIRECTORY
      - run: echo "Successfully deployed to bucket accessible to cloudfront"
workflows:
  version: 2
  build-publish-and-deploy:
    jobs:
      - build-deploy-prod:
          filters:
            branches:
              only:
                - main
